### ISSUE TITLE
Crash while consuming data

### ISSUE THREAD

**Issue by lbaey** [BenPru/novus300_Rs485#4]
With defaut config, novus300bus crashes on my installation... did you  encounter this issue ?

Logger: homeassistant.components.sensor
Source: custom_components/novus300bus/sensor.py:148
Integration: Capteur (documentation, issues)
First occurred: 22:28:25 (1 occurrences)
Last logged: 22:28:25

```
Error while setting up novus300bus platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 289, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/novus300bus/sensor.py", line 237, in async_setup_platform
    await serial_read(port, baudrate, timeout=0, stopbits=STOPBITS_ONE, parity=PARITY_MARK, bytesize=EIGHTBITS, rtscts=False, dsrdtr=False)
  File "/config/custom_components/novus300bus/sensor.py", line 120, in serial_read
    result = consumePackage(data)
  File "/config/custom_components/novus300bus/sensor.py", line 148, in consumePackage
    while not isCommand(data[2]):
IndexError: list index out of range

```

**Comment by BenPru** [comment]
Please try the current version. Thanks.
I can not test this because I'm no more using this integration.
It is not running in a own thread and slow down the complete ha installation and the RS485 bus. For me my novus is getting unstable with it.
